name: setup-node-install
description: "Setup Node and install deps"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - shell: bash
      run: npm ci || npm i
