name: CI pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm i

      - name: ESLint
        run: npm run lint --if-present

      - name: Prettier check
        run: npm run prettier --if-present -- -c .

      - name: Run tests with coverage
        run: npm test --if-present -- --coverage --ci

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/**
            junit.xml
          if-no-files-found: warn

      # Public repos don’t need token; private would use CODECOV_TOKEN secret
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/**
            build/**
          if-no-files-found: warn
