name: CI pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup & install (composite)
        uses: ./.github/actions/setup-node-install

      - name: ESLint
        run: npm run lint || npm run eslint --if-present

      - name: Prettier check
        run: npm run prettier:check || npx prettier --check .

      - name: Run tests with coverage
        run: npm test --if-present -- --coverage --ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
